# https://github.com/uxber
#
# Description: Build DockerImages using GitHub Actions
#
# {{github.repository}} as <account>/<repo>

name: Clash Premium Dispatch

on:
  workflow_dispatch:
    inputs:
      clash_version:
        description: "Clash Premium Version"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker Buildx

    steps:
      - name: Initialization environment
        id: init
        run: |
          echo "image_name=fengdingwen/clash" >> $GITHUB_OUTPUT 
          echo "version=${{ inputs.clash_version }}" >> $GITHUB_OUTPUT
          echo "platform=linux/arm64,linux/amd64" >> $GITHUB_OUTPUT          

      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Set up QEMU Simulator
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ steps.init.outputs.image_name }}
          tags: |
            type=raw,value=${{ inputs.clash_version }}
            type=raw,value=latest

      - name: Build and Publish image
        uses: docker/build-push-action@master
        with:
          push: true
          context: docker
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ steps.init.outputs.platform }}
          build-args: |
            CLASH_PREMIUM_VERSION=${{ steps.init.outputs.version }}
